title:              Aditi Rupade
email:              aditi.rupade77@gmail.com
description:        Quantum Enthusiast
author:             Start Bootstrap
baseurl:            "/"
url:                "https://aditirupade.github.io"

# Social Profiles
twitter_username:   AditiRupade
github_username:    AditiRupade 
linkedin_username:  aditi-rupade-7108a5127

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
